<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBooksMacBook.lan" failures="1" tests="1" name="TestAdd_RemoveCat2" time="6.605" errors="0" timestamp="2020-11-23T22:28:16 CST">
  <testcase classname="com.tfAutomationProject.testCases.TC_DuplicateCategory_002" name="addCategory" time="3.163">
    <failure type="java.lang.AssertionError" message="expected [The category you want to add already exists:] but found [Are you sure you wish to remove Test1980?

Yes or Nevermind]">
      <![CDATA[java.lang.AssertionError: expected [The category you want to add already exists:] but found [Are you sure you wish to remove Test1980?

Yes or Nevermind]
at com.tfAutomationProject.testCases.TC_DuplicateCategory_002.addCategory(TC_DuplicateCategory_002.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- addCategory -->
</testsuite> <!-- TestAdd_RemoveCat2 -->
